# permissions for end users to view mirroreds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrored-viewer-role
rules:
- apiGroups:
  - mirror.alklabs.com
  resources:
  - mirroreds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.alklabs.com
  resources:
  - mirroreds/status
  verbs:
  - get
